"""Negentropy 合并初始迁移

Revision ID: 0001
Revises:
Create Date: 2026-04-08 00:00:00.000000+00:00

本迁移文件从 ORM 模型定义（Base.metadata）重新生成，一次性创建全部
42 张业务表、索引、约束、枚举类型、序列、触发器和种子数据。

变更范围:
  - Pulse / Internalization / Perception / State / Action
  - Observability / Security / Plugin Ecosystem / Model Config / Knowledge Runtime
  - 共 42 张表、3 个枚举、1 个序列、HNSW/GIN/部分索引、TSVECTOR 触发器
  - 种子数据：model_configs 默认模型 × 2 + negentropy-perceives MCP 预设
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import negentropy.models.base

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # =========================================================================
    # 前置 DDL：创建序列（events.sequence_num 依赖此序列）
    # =========================================================================
    op.execute(sa.text("CREATE SEQUENCE IF NOT EXISTS negentropy.events_sequence_num_seq"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_states",
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("app_name"),
        schema="negentropy",
    )
    op.create_table(
        "corpus",
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("corpus_type", sa.String(length=50), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("parent_corpus_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["parent_corpus_id"], ["negentropy.corpus.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_name", "name", name="corpus_app_name_unique"),
        schema="negentropy",
    )
    op.create_table(
        "credentials",
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("credential_key", sa.String(length=255), nullable=False),
        sa.Column("credential_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("app_name", "user_id", "credential_key"),
        schema="negentropy",
    )
    op.create_index(
        "ix_negentropy_credentials_app_name", "credentials", ["app_name"], unique=False, schema="negentropy"
    )
    op.create_index(
        "ix_negentropy_credentials_credential_key", "credentials", ["credential_key"], unique=False, schema="negentropy"
    )
    op.create_index("ix_negentropy_credentials_user_id", "credentials", ["user_id"], unique=False, schema="negentropy")
    op.create_table(
        "instructions",
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("instruction_key", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_name", "instruction_key", "version", name="instructions_app_key_version_unique"),
        schema="negentropy",
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("corpus_id", sa.UUID(), nullable=False),
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("gcs_uri", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("markdown_content", sa.Text(), nullable=True),
        sa.Column("markdown_gcs_uri", sa.Text(), nullable=True),
        sa.Column("markdown_extract_status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("markdown_extract_error", sa.Text(), nullable=True),
        sa.Column("markdown_extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        # source_id 列延后添加（与 doc_sources 存在循环依赖）
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["corpus_id"], ["negentropy.corpus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("corpus_id", "file_hash", name="uq_knowledge_documents_corpus_hash"),
        schema="negentropy",
    )
    op.create_index(
        "ix_knowledge_documents_app_name", "knowledge_documents", ["app_name"], unique=False, schema="negentropy"
    )
    op.create_index(
        "ix_knowledge_documents_markdown_extract_status",
        "knowledge_documents",
        ["markdown_extract_status"],
        unique=False,
        schema="negentropy",
    )
    op.create_index(
        "ix_knowledge_documents_status", "knowledge_documents", ["status"], unique=False, schema="negentropy"
    )
    # doc_sources 依赖 knowledge_documents（FK: document_id → knowledge_documents.id），
    # 故在此处创建，并随后添加 knowledge_documents.source_id → doc_sources.id
    op.create_table(
        "doc_sources",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("original_url", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("extracted_summary", sa.Text(), nullable=True),
        sa.Column("extraction_duration_ms", sa.Integer(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extractor_tool_name", sa.String(length=100), nullable=True),
        sa.Column("extractor_server_id", sa.String(length=100), nullable=True),
        sa.Column("raw_metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["negentropy.knowledge_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_index("ix_doc_sources_document_id", "doc_sources", ["document_id"], unique=False, schema="negentropy")
    op.create_index("ix_doc_sources_source_type", "doc_sources", ["source_type"], unique=False, schema="negentropy")
    # 延后添加 knowledge_documents.source_id（解决循环 FK）
    op.add_column(
        "knowledge_documents",
        sa.Column("source_id", sa.UUID(), nullable=True),
        schema="negentropy",
    )
    op.create_foreign_key(
        "fk_knowledge_documents_source_id",
        "knowledge_documents",
        "doc_sources",
        ["source_id"],
        ["id"],
        ondelete="SET NULL",
        source_schema="negentropy",
        referent_schema="negentropy",
    )
    op.create_index(
        "ix_knowledge_documents_source_id", "knowledge_documents", ["source_id"], unique=False, schema="negentropy"
    )
    op.create_table(
        "knowledge_graph_runs",
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("run_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_name", "idempotency_key", name="knowledge_graph_runs_idempotency_unique"),
        sa.UniqueConstraint("app_name", "run_id", name="knowledge_graph_runs_app_run_unique"),
        schema="negentropy",
    )
    op.create_table(
        "knowledge_pipeline_runs",
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("run_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_name", "idempotency_key", name="knowledge_pipeline_runs_idempotency_unique"),
        sa.UniqueConstraint("app_name", "run_id", name="knowledge_pipeline_runs_app_run_unique"),
        schema="negentropy",
    )
    op.create_table(
        "mcp_servers",
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum("PRIVATE", "SHARED", "PUBLIC", name="pluginvisibility", schema="negentropy"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("transport_type", sa.String(length=50), nullable=False),
        sa.Column("command", sa.Text(), nullable=True),
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=True),
        sa.Column("env", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("is_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("auto_start", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="mcp_servers_name_unique"),
        schema="negentropy",
    )
    op.create_index("ix_mcp_servers_owner", "mcp_servers", ["owner_id"], unique=False, schema="negentropy")
    op.create_index("ix_mcp_servers_visibility", "mcp_servers", ["visibility"], unique=False, schema="negentropy")
    op.create_table(
        "memory_audit_logs",
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("memory_id", sa.String(length=255), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "app_name", "user_id", "memory_id", "idempotency_key", name="memory_audit_logs_idempotency_unique"
        ),
        schema="negentropy",
    )
    op.create_table(
        "memory_automation_configs",
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_name"),
        schema="negentropy",
    )
    op.create_table(
        "model_configs",
        sa.Column(
            "model_type",
            sa.Enum("llm", "embedding", "rerank", name="model_type_enum", schema="negentropy"),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("vendor", sa.String(length=50), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vendor", "model_name", "model_type", name="model_configs_vendor_model_type_unique"),
        schema="negentropy",
    )
    op.create_index(
        "ix_model_configs_default_unique",
        "model_configs",
        ["model_type"],
        unique=True,
        schema="negentropy",
        postgresql_where=sa.text("is_default IS true"),
    )
    op.create_table(
        "plugin_permissions",
        sa.Column("plugin_type", sa.String(length=50), nullable=False),
        sa.Column("plugin_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column(
            "permission", sa.Enum("VIEW", "EDIT", name="pluginpermissiontype", schema="negentropy"), nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plugin_type", "plugin_id", "user_id", name="plugin_permissions_unique"),
        schema="negentropy",
    )
    op.create_index(
        "ix_plugin_permissions_plugin",
        "plugin_permissions",
        ["plugin_type", "plugin_id"],
        unique=False,
        schema="negentropy",
    )
    op.create_index("ix_plugin_permissions_user", "plugin_permissions", ["user_id"], unique=False, schema="negentropy")
    op.create_table(
        "sandbox_executions",
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("sandbox_type", sa.String(length=50), nullable=True),
        sa.Column("code", sa.Text(), nullable=True),
        sa.Column("environment", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("stdout", sa.Text(), nullable=True),
        sa.Column("stderr", sa.Text(), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("execution_time_ms", sa.Float(), nullable=True),
        sa.Column("resource_usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_table(
        "skills",
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum("PRIVATE", "SHARED", "PUBLIC", name="pluginvisibility", schema="negentropy"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=100), server_default="general", nullable=False),
        sa.Column("version", sa.String(length=50), server_default="1.0.0", nullable=False),
        sa.Column("prompt_template", sa.Text(), nullable=True),
        sa.Column("config_schema", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("default_config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("required_tools", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=True),
        sa.Column("is_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="skills_name_unique"),
        schema="negentropy",
    )
    op.create_index("ix_skills_category", "skills", ["category"], unique=False, schema="negentropy")
    op.create_index("ix_skills_owner", "skills", ["owner_id"], unique=False, schema="negentropy")
    op.create_table(
        "sub_agents",
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum("PRIVATE", "SHARED", "PUBLIC", name="pluginvisibility", schema="negentropy"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("agent_type", sa.String(length=100), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("skills", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=True),
        sa.Column("tools", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=True),
        sa.Column("is_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="sub_agents_name_unique"),
        schema="negentropy",
    )
    op.create_index("ix_sub_agents_owner", "sub_agents", ["owner_id"], unique=False, schema="negentropy")
    op.create_table(
        "threads",
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_name", "user_id", "id", name="threads_app_user_unique"),
        schema="negentropy",
    )
    op.create_table(
        "tools",
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("openapi_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("permissions", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("call_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("avg_latency_ms", sa.Float(), server_default="0", nullable=False),
        sa.Column("call_count_success", sa.Integer(), server_default="0", nullable=False),
        sa.Column("call_count_failed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("call_count_denied", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_name", "name", name="tools_app_name_unique"),
        schema="negentropy",
    )
    op.create_table(
        "traces",
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("span_id", sa.String(length=16), nullable=False),
        sa.Column("parent_span_id", sa.String(length=16), nullable=True),
        sa.Column("operation_name", sa.String(length=255), nullable=False),
        sa.Column("span_kind", sa.String(length=20), server_default="INTERNAL", nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("events", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ns", sa.BigInteger(), nullable=True),
        sa.Column("status_code", sa.String(length=10), server_default="UNSET", nullable=True),
        sa.Column("status_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_table(
        "user_states",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "app_name"),
        schema="negentropy",
    )
    op.create_table(
        "consolidation_jobs",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["negentropy.threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_table(
        "corpus_versions",
        sa.Column("corpus_id", sa.UUID(), nullable=False),
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("document_count", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("config_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trigger_type", sa.String(length=50), server_default="manual", nullable=False),
        sa.Column("build_run_id", sa.String(length=255), nullable=True),
        sa.Column("diff_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["corpus_id"], ["negentropy.corpus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("corpus_id", "version_number", name="uq_corpus_ver"),
        schema="negentropy",
    )
    op.create_index("ix_corpus_versions_corpus_id", "corpus_versions", ["corpus_id"], unique=False, schema="negentropy")
    op.create_index("ix_corpus_versions_status", "corpus_versions", ["status"], unique=False, schema="negentropy")
    op.create_table(
        "doc_catalog_nodes",
        sa.Column("corpus_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("node_type", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["corpus_id"], ["negentropy.corpus.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["negentropy.doc_catalog_nodes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("corpus_id", "parent_id", "name", name="uq_catalog_sibling_name"),
        sa.UniqueConstraint("corpus_id", "slug", name="uq_catalog_corpus_slug"),
        schema="negentropy",
    )
    op.create_index(
        "ix_doc_catalog_nodes_corpus_id", "doc_catalog_nodes", ["corpus_id"], unique=False, schema="negentropy"
    )
    op.create_index(
        "ix_doc_catalog_nodes_parent_id", "doc_catalog_nodes", ["parent_id"], unique=False, schema="negentropy"
    )
    op.create_table(
        "events",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("invocation_id", sa.UUID(), nullable=False),
        sa.Column("author", sa.String(length=50), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("actions", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "sequence_num",
            sa.Integer(),
            server_default=sa.text("nextval('negentropy.events_sequence_num_seq'::regclass)"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["negentropy.threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_table(
        "facts",
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("fact_type", sa.String(length=50), server_default="preference", nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding", negentropy.models.base.Vector(dim=1536), nullable=True),
        sa.Column("confidence", sa.Float(), server_default="1.0", nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["negentropy.threads.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "app_name", "fact_type", "key", name="facts_user_key_unique"),
        schema="negentropy",
    )
    op.create_table(
        "kg_entities",
        sa.Column("corpus_id", sa.UUID(), nullable=False),
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("canonical_name", sa.String(length=500), nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("embedding", negentropy.models.base.Vector(dim=1536), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("mention_count", sa.Integer(), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["corpus_id"], ["negentropy.corpus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("corpus_id", "canonical_name", name="uq_kg_entity_corpus_name"),
        schema="negentropy",
    )
    op.create_index("ix_kg_entities_confidence", "kg_entities", ["confidence"], unique=False, schema="negentropy")
    op.create_index(
        "ix_kg_entities_corpus_type", "kg_entities", ["corpus_id", "entity_type"], unique=False, schema="negentropy"
    )
    op.create_table(
        "knowledge",
        sa.Column("corpus_id", sa.UUID(), nullable=False),
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", negentropy.models.base.Vector(dim=1536), nullable=True),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("source_uri", sa.Text(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column("character_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("retrieval_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_confidence", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["corpus_id"], ["negentropy.corpus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_table(
        "mcp_tools",
        sa.Column("server_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("input_schema", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("output_schema", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("icons", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("annotations", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("execution", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("call_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["server_id"], ["negentropy.mcp_servers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("server_id", "name", name="mcp_tools_server_name_unique"),
        schema="negentropy",
    )
    op.create_index("ix_mcp_tools_server_id", "mcp_tools", ["server_id"], unique=False, schema="negentropy")
    op.create_table(
        "mcp_trial_assets",
        sa.Column("server_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column("source_kind", sa.String(length=50), server_default="upload", nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=True),
        sa.Column("size_bytes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("gcs_uri", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["server_id"], ["negentropy.mcp_servers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_index(
        "ix_mcp_trial_assets_owner_created",
        "mcp_trial_assets",
        ["owner_id", "created_at"],
        unique=False,
        schema="negentropy",
    )
    op.create_index(
        "ix_mcp_trial_assets_server_created",
        "mcp_trial_assets",
        ["server_id", "created_at"],
        unique=False,
        schema="negentropy",
    )
    op.create_table(
        "memories",
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("memory_type", sa.String(length=50), server_default="episodic", nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", negentropy.models.base.Vector(dim=1536), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("retention_score", sa.Float(), server_default="1.0", nullable=False),
        sa.Column("access_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["negentropy.threads.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_table(
        "runs",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("thinking_steps", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=True),
        sa.Column("tool_calls", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["negentropy.threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_table(
        "snapshots",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("events_summary", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["negentropy.threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("thread_id", "version", name="snapshots_thread_version_unique"),
        schema="negentropy",
    )
    op.create_table(
        "tool_executions",
        sa.Column("tool_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("input_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tool_id"],
            ["negentropy.tools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_table(
        "wiki_publications",
        sa.Column("corpus_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("theme", sa.String(length=20), server_default="default", nullable=False),
        sa.Column("navigation_config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("custom_css", sa.Text(), nullable=True),
        sa.Column("custom_js", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["corpus_id"], ["negentropy.corpus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("corpus_id", "slug", name="uq_wiki_pub_corpus_slug"),
        schema="negentropy",
    )
    op.create_index(
        "ix_wiki_publications_corpus_id", "wiki_publications", ["corpus_id"], unique=False, schema="negentropy"
    )
    op.create_index("ix_wiki_publications_status", "wiki_publications", ["status"], unique=False, schema="negentropy")
    op.create_table(
        "doc_catalog_memberships",
        sa.Column("catalog_node_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["catalog_node_id"], ["negentropy.doc_catalog_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["negentropy.knowledge_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("catalog_node_id", "document_id", name="uq_catalog_membership_unique"),
        schema="negentropy",
    )
    op.create_index(
        "ix_catalog_memberships_document_id",
        "doc_catalog_memberships",
        ["document_id"],
        unique=False,
        schema="negentropy",
    )
    op.create_table(
        "kg_entity_mentions",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("corpus_id", sa.UUID(), nullable=False),
        sa.Column("knowledge_chunk_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("context_snippet", sa.Text(), nullable=True),
        sa.Column("char_offset", sa.Integer(), nullable=True),
        sa.Column("char_length", sa.Integer(), nullable=True),
        sa.Column("extraction_method", sa.String(length=50), nullable=False),
        sa.Column("extraction_confidence", sa.Float(), nullable=False),
        sa.Column("extractor_model", sa.String(length=255), nullable=True),
        sa.Column("build_run_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["corpus_id"], ["negentropy.corpus.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["negentropy.knowledge_documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["entity_id"], ["negentropy.kg_entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["knowledge_chunk_id"], ["negentropy.knowledge.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_index(
        "ix_kg_mentions_chunk", "kg_entity_mentions", ["knowledge_chunk_id"], unique=False, schema="negentropy"
    )
    op.create_index("ix_kg_mentions_corpus", "kg_entity_mentions", ["corpus_id"], unique=False, schema="negentropy")
    op.create_index("ix_kg_mentions_document", "kg_entity_mentions", ["document_id"], unique=False, schema="negentropy")
    op.create_index("ix_kg_mentions_entity", "kg_entity_mentions", ["entity_id"], unique=False, schema="negentropy")
    op.create_table(
        "kg_relations",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("corpus_id", sa.UUID(), nullable=False),
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("relation_type", sa.String(length=50), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence_text", sa.Text(), nullable=True),
        sa.Column("evidence_chunk_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("first_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["corpus_id"], ["negentropy.corpus.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["negentropy.kg_entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["negentropy.kg_entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "target_id", "relation_type", name="uq_kg_relation_src_tgt_type"),
        schema="negentropy",
    )
    op.create_index("ix_kg_relations_corpus", "kg_relations", ["corpus_id"], unique=False, schema="negentropy")
    op.create_index("ix_kg_relations_source", "kg_relations", ["source_id"], unique=False, schema="negentropy")
    op.create_index("ix_kg_relations_target", "kg_relations", ["target_id"], unique=False, schema="negentropy")
    op.create_index("ix_kg_relations_type", "kg_relations", ["relation_type"], unique=False, schema="negentropy")
    op.create_table(
        "knowledge_feedback",
        sa.Column("knowledge_id", sa.UUID(), nullable=False),
        sa.Column("corpus_id", sa.UUID(), nullable=False),
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("agent_id", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("query_text", sa.Text(), nullable=True),
        sa.Column("query_mode", sa.String(length=20), nullable=True),
        sa.Column("feedback_type", sa.String(length=20), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["corpus_id"], ["negentropy.corpus.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["knowledge_id"], ["negentropy.knowledge.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_index("ix_kb_feedback_corpus", "knowledge_feedback", ["corpus_id"], unique=False, schema="negentropy")
    op.create_index("ix_kb_feedback_created", "knowledge_feedback", ["created_at"], unique=False, schema="negentropy")
    op.create_index(
        "ix_kb_feedback_knowledge", "knowledge_feedback", ["knowledge_id"], unique=False, schema="negentropy"
    )
    op.create_index("ix_kb_feedback_session", "knowledge_feedback", ["session_id"], unique=False, schema="negentropy")
    op.create_index("ix_kb_feedback_type", "knowledge_feedback", ["feedback_type"], unique=False, schema="negentropy")
    op.create_table(
        "mcp_tool_runs",
        sa.Column("server_id", sa.UUID(), nullable=False),
        sa.Column("tool_id", sa.UUID(), nullable=True),
        sa.Column("tool_name", sa.String(length=255), nullable=False),
        sa.Column("origin", sa.String(length=50), server_default="trial_ui", nullable=False),
        sa.Column("status", sa.String(length=50), server_default="running", nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("request_payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column(
            "normalized_request_payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("result_payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["server_id"], ["negentropy.mcp_servers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tool_id"], ["negentropy.mcp_tools.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_index(
        "ix_mcp_tool_runs_origin_started", "mcp_tool_runs", ["origin", "started_at"], unique=False, schema="negentropy"
    )
    op.create_index(
        "ix_mcp_tool_runs_server_tool_started",
        "mcp_tool_runs",
        ["server_id", "tool_name", "started_at"],
        unique=False,
        schema="negentropy",
    )
    op.create_table(
        "messages",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", negentropy.models.base.Vector(dim=1536), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["negentropy.events.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["thread_id"], ["negentropy.threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_table(
        "wiki_publication_entries",
        sa.Column("publication_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("entry_slug", sa.String(length=255), nullable=False),
        sa.Column("entry_title", sa.String(length=500), nullable=True),
        sa.Column("entry_order", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_index_page", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["negentropy.knowledge_documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["publication_id"], ["negentropy.wiki_publications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("publication_id", "document_id", name="uq_wiki_entry_pub_doc"),
        sa.UniqueConstraint("publication_id", "entry_slug", name="uq_wiki_entry_pub_slug"),
        schema="negentropy",
    )
    op.create_table(
        "mcp_tool_run_events",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("sequence_num", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), server_default="info", nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("duration_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["negentropy.mcp_tool_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "sequence_num", name="mcp_tool_run_events_run_seq_unique"),
        schema="negentropy",
    )
    op.create_index(
        "ix_mcp_tool_run_events_run_timestamp",
        "mcp_tool_run_events",
        ["run_id", "timestamp"],
        unique=False,
        schema="negentropy",
    )
    # ### end Alembic commands ###

    # =========================================================================
    # 手动补充：autogenerate 无法捕获的非 ORM 概念
    # =========================================================================

    # HNSW 向量索引（ORM 的 postgresql_with 参数不被 autogenerate 支持）
    op.execute(
        sa.text(
            "CREATE INDEX IF NOT EXISTS ix_kg_entities_embedding"
            " ON negentropy.kg_entities"
            " USING hnsw (embedding vector_cosine_ops)"
            " WITH (m = 16, ef_construction = 64)"
        )
    )

    # GIN 索引：knowledge.search_vector 全文搜索（未在 ORM __table_args__ 中声明）
    op.create_index(
        "ix_negentropy_knowledge_search_vector",
        "knowledge",
        ["search_vector"],
        unique=False,
        schema="negentropy",
        postgresql_using="gin",
    )

    # 部分索引：entity_type 非空时（未在 ORM 中声明）
    op.execute(
        sa.text(
            "CREATE INDEX IF NOT EXISTS idx_kb_entity_type"
            " ON negentropy.knowledge(entity_type)"
            " WHERE entity_type IS NOT NULL"
        )
    )

    # TSVECTOR 触发器：自动从 content 更新 search_vector（非 ORM 概念）
    op.execute(
        sa.text(
            "CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE"
            " ON negentropy.knowledge FOR EACH ROW EXECUTE FUNCTION"
            " tsvector_update_trigger(search_vector, 'pg_catalog.english', content)"
        )
    )

    # =========================================================================
    # 种子数据
    # =========================================================================

    # model_configs 默认模型配置
    model_type_col = postgresql.ENUM(
        "llm",
        "embedding",
        "rerank",
        name="model_type_enum",
        schema="negentropy",
        create_type=False,
    )
    model_configs = sa.table(
        "model_configs",
        sa.column("model_type", model_type_col),
        sa.column("display_name", sa.String),
        sa.column("vendor", sa.String),
        sa.column("model_name", sa.String),
        sa.column("is_default", sa.Boolean),
        sa.column("enabled", sa.Boolean),
        sa.column("config", postgresql.JSONB),
        schema="negentropy",
    )
    op.bulk_insert(
        model_configs,
        [
            {
                "model_type": "llm",
                "display_name": "GLM-5 (智谱)",
                "vendor": "zai",
                "model_name": "glm-5",
                "is_default": True,
                "enabled": True,
                "config": {"temperature": 0.7},
            },
            {
                "model_type": "embedding",
                "display_name": "Text Embedding 005 (Vertex AI)",
                "vendor": "vertex_ai",
                "model_name": "text-embedding-005",
                "is_default": True,
                "enabled": True,
                "config": {},
            },
        ],
    )

    # Negentropy Perceives MCP Server 预设（幂等 upsert）
    op.execute(
        sa.text("""
        INSERT INTO negentropy.mcp_servers (
            owner_id, visibility, name, display_name, description,
            transport_type, command, args, env, url, headers,
            is_enabled, auto_start, config
        )
        VALUES (
            'system:negentropy-perceives-preset',
            'PUBLIC'::negentropy.pluginvisibility,
            'negentropy-perceives',
            'Negentropy Perceives',
            '一款商用级 MCP Server，能够从网页和 PDF 文件中精准提取包括文本、'
            '图片、表格、公式等内容，并将之转换为与源文档编排格式一致的 Markdown 文档。',
            'http',
            NULL,
            '[]'::jsonb,
            '{}'::jsonb,
            'http://localhost:8081/mcp',
            '{}'::jsonb,
            TRUE,
            TRUE,
            '{}'::jsonb
        )
        ON CONFLICT (name) DO UPDATE
        SET
            owner_id = EXCLUDED.owner_id,
            visibility = EXCLUDED.visibility,
            display_name = EXCLUDED.display_name,
            description = EXCLUDED.description,
            transport_type = EXCLUDED.transport_type,
            command = EXCLUDED.command,
            args = EXCLUDED.args,
            env = EXCLUDED.env,
            url = EXCLUDED.url,
            headers = EXCLUDED.headers,
            is_enabled = EXCLUDED.is_enabled,
            auto_start = EXCLUDED.auto_start,
            config = EXCLUDED.config,
            updated_at = now()
    """)
    )


def downgrade() -> None:
    # =========================================================================
    # 前置清理：删除 upgrade 中手动创建的非 ORM 对象（逆序）
    # =========================================================================

    # 删除 TSVECTOR 触发器
    op.execute(sa.text("DROP TRIGGER IF EXISTS tsvectorupdate ON negentropy.knowledge"))

    # 删除 HNSW 向量索引
    op.execute(sa.text("DROP INDEX IF EXISTS negentropy.ix_kg_entities_embedding"))

    # 删除 GIN 索引
    op.drop_index(
        "ix_negentropy_knowledge_search_vector",
        table_name="knowledge",
        schema="negentropy",
    )

    # 删除部分索引
    op.execute(sa.text("DROP INDEX IF EXISTS negentropy.idx_kb_entity_type"))

    # 删除循环 FK：先删约束和列，再由 autogenerate 删对应表
    # 1) knowledge_documents.source_id → doc_sources.id（upgrade 中延后添加的）
    op.drop_constraint(
        "fk_knowledge_documents_source_id",
        "knowledge_documents",
        type_="foreignkey",
        schema="negentropy",
    )
    op.drop_column("knowledge_documents", "source_id", schema="negentropy")

    # 2) doc_sources.document_id → knowledge_documents.id（阻止先删 knowledge_documents）
    op.drop_constraint(
        "doc_sources_document_id_fkey",
        "doc_sources",
        type_="foreignkey",
        schema="negentropy",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mcp_tool_run_events_run_timestamp", table_name="mcp_tool_run_events", schema="negentropy")
    op.drop_table("mcp_tool_run_events", schema="negentropy")
    op.drop_table("wiki_publication_entries", schema="negentropy")
    op.drop_table("messages", schema="negentropy")
    op.drop_index("ix_mcp_tool_runs_server_tool_started", table_name="mcp_tool_runs", schema="negentropy")
    op.drop_index("ix_mcp_tool_runs_origin_started", table_name="mcp_tool_runs", schema="negentropy")
    op.drop_table("mcp_tool_runs", schema="negentropy")
    op.drop_index("ix_kb_feedback_type", table_name="knowledge_feedback", schema="negentropy")
    op.drop_index("ix_kb_feedback_session", table_name="knowledge_feedback", schema="negentropy")
    op.drop_index("ix_kb_feedback_knowledge", table_name="knowledge_feedback", schema="negentropy")
    op.drop_index("ix_kb_feedback_created", table_name="knowledge_feedback", schema="negentropy")
    op.drop_index("ix_kb_feedback_corpus", table_name="knowledge_feedback", schema="negentropy")
    op.drop_table("knowledge_feedback", schema="negentropy")
    op.drop_index("ix_kg_relations_type", table_name="kg_relations", schema="negentropy")
    op.drop_index("ix_kg_relations_target", table_name="kg_relations", schema="negentropy")
    op.drop_index("ix_kg_relations_source", table_name="kg_relations", schema="negentropy")
    op.drop_index("ix_kg_relations_corpus", table_name="kg_relations", schema="negentropy")
    op.drop_table("kg_relations", schema="negentropy")
    op.drop_index("ix_kg_mentions_entity", table_name="kg_entity_mentions", schema="negentropy")
    op.drop_index("ix_kg_mentions_document", table_name="kg_entity_mentions", schema="negentropy")
    op.drop_index("ix_kg_mentions_corpus", table_name="kg_entity_mentions", schema="negentropy")
    op.drop_index("ix_kg_mentions_chunk", table_name="kg_entity_mentions", schema="negentropy")
    op.drop_table("kg_entity_mentions", schema="negentropy")
    op.drop_index("ix_catalog_memberships_document_id", table_name="doc_catalog_memberships", schema="negentropy")
    op.drop_table("doc_catalog_memberships", schema="negentropy")
    op.drop_index("ix_wiki_publications_status", table_name="wiki_publications", schema="negentropy")
    op.drop_index("ix_wiki_publications_corpus_id", table_name="wiki_publications", schema="negentropy")
    op.drop_table("wiki_publications", schema="negentropy")
    op.drop_table("tool_executions", schema="negentropy")
    op.drop_table("snapshots", schema="negentropy")
    op.drop_table("runs", schema="negentropy")
    op.drop_table("memories", schema="negentropy")
    op.drop_index("ix_mcp_trial_assets_server_created", table_name="mcp_trial_assets", schema="negentropy")
    op.drop_index("ix_mcp_trial_assets_owner_created", table_name="mcp_trial_assets", schema="negentropy")
    op.drop_table("mcp_trial_assets", schema="negentropy")
    op.drop_index("ix_mcp_tools_server_id", table_name="mcp_tools", schema="negentropy")
    op.drop_table("mcp_tools", schema="negentropy")
    op.drop_table("knowledge", schema="negentropy")
    op.drop_index("ix_kg_entities_corpus_type", table_name="kg_entities", schema="negentropy")
    op.drop_index("ix_kg_entities_confidence", table_name="kg_entities", schema="negentropy")
    op.drop_table("kg_entities", schema="negentropy")
    op.drop_table("facts", schema="negentropy")
    op.drop_table("events", schema="negentropy")
    op.drop_index("ix_doc_catalog_nodes_parent_id", table_name="doc_catalog_nodes", schema="negentropy")
    op.drop_index("ix_doc_catalog_nodes_corpus_id", table_name="doc_catalog_nodes", schema="negentropy")
    op.drop_table("doc_catalog_nodes", schema="negentropy")
    op.drop_index("ix_corpus_versions_status", table_name="corpus_versions", schema="negentropy")
    op.drop_index("ix_corpus_versions_corpus_id", table_name="corpus_versions", schema="negentropy")
    op.drop_table("corpus_versions", schema="negentropy")
    op.drop_table("consolidation_jobs", schema="negentropy")
    op.drop_table("user_states", schema="negentropy")
    op.drop_table("traces", schema="negentropy")
    op.drop_table("tools", schema="negentropy")
    op.drop_table("threads", schema="negentropy")
    op.drop_index("ix_sub_agents_owner", table_name="sub_agents", schema="negentropy")
    op.drop_table("sub_agents", schema="negentropy")
    op.drop_index("ix_skills_owner", table_name="skills", schema="negentropy")
    op.drop_index("ix_skills_category", table_name="skills", schema="negentropy")
    op.drop_table("skills", schema="negentropy")
    op.drop_table("sandbox_executions", schema="negentropy")
    op.drop_index("ix_plugin_permissions_user", table_name="plugin_permissions", schema="negentropy")
    op.drop_index("ix_plugin_permissions_plugin", table_name="plugin_permissions", schema="negentropy")
    op.drop_table("plugin_permissions", schema="negentropy")
    op.drop_index(
        "ix_model_configs_default_unique",
        table_name="model_configs",
        schema="negentropy",
        postgresql_where=sa.text("is_default IS true"),
    )
    op.drop_table("model_configs", schema="negentropy")
    op.drop_table("memory_automation_configs", schema="negentropy")
    op.drop_table("memory_audit_logs", schema="negentropy")
    op.drop_index("ix_mcp_servers_visibility", table_name="mcp_servers", schema="negentropy")
    op.drop_index("ix_mcp_servers_owner", table_name="mcp_servers", schema="negentropy")
    op.drop_table("mcp_servers", schema="negentropy")
    op.drop_table("knowledge_pipeline_runs", schema="negentropy")
    op.drop_table("knowledge_graph_runs", schema="negentropy")
    op.drop_index("ix_knowledge_documents_status", table_name="knowledge_documents", schema="negentropy")
    # ix_knowledge_documents_source_id 已随 source_id 列的 DROP 级联删除（前置清理中）
    op.drop_index(
        "ix_knowledge_documents_markdown_extract_status", table_name="knowledge_documents", schema="negentropy"
    )
    op.drop_index("ix_knowledge_documents_app_name", table_name="knowledge_documents", schema="negentropy")
    op.drop_table("knowledge_documents", schema="negentropy")
    op.drop_table("instructions", schema="negentropy")
    op.drop_index("ix_doc_sources_source_type", table_name="doc_sources", schema="negentropy")
    op.drop_index("ix_doc_sources_document_id", table_name="doc_sources", schema="negentropy")
    op.drop_table("doc_sources", schema="negentropy")
    op.drop_index("ix_negentropy_credentials_user_id", table_name="credentials", schema="negentropy")
    op.drop_index("ix_negentropy_credentials_credential_key", table_name="credentials", schema="negentropy")
    op.drop_index("ix_negentropy_credentials_app_name", table_name="credentials", schema="negentropy")
    op.drop_table("credentials", schema="negentropy")
    op.drop_table("corpus", schema="negentropy")
    op.drop_table("app_states", schema="negentropy")
    # ### end Alembic commands ###

    # =========================================================================
    # 后置清理：删除序列和枚举类型
    # =========================================================================

    # 删除序列
    op.execute(sa.text("DROP SEQUENCE IF EXISTS negentropy.events_sequence_num_seq"))

    # 删除枚举类型（防止 re-upgrade 时 DuplicateObjectError）
    op.execute(sa.text("DROP TYPE IF EXISTS negentropy.model_type_enum"))
    op.execute(sa.text("DROP TYPE IF EXISTS negentropy.pluginpermissiontype"))
    op.execute(sa.text("DROP TYPE IF EXISTS negentropy.pluginvisibility"))
