"""Init Schema

Revision ID: 093a93971bf5
Revises:
Create Date: 2026-02-02 05:57:25.308107+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Register custom types (e.g. Vector) for Alembic autogenerate
import negentropy.models.base
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "093a93971bf5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_states",
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("app_name"),
        schema="negentropy",
    )
    op.create_table(
        "corpus",
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_name", "name", name="corpus_app_name_unique"),
        schema="negentropy",
    )
    op.create_table(
        "credentials",
        sa.Column("app_name", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("credential_key", sa.String(), nullable=False),
        sa.Column("credential_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("app_name", "user_id", "credential_key"),
        schema="negentropy",
    )
    op.create_index(
        op.f("ix_negentropy_credentials_app_name"), "credentials", ["app_name"], unique=False, schema="negentropy"
    )
    op.create_index(
        op.f("ix_negentropy_credentials_credential_key"),
        "credentials",
        ["credential_key"],
        unique=False,
        schema="negentropy",
    )
    op.create_index(
        op.f("ix_negentropy_credentials_user_id"), "credentials", ["user_id"], unique=False, schema="negentropy"
    )
    op.create_table(
        "instructions",
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("instruction_key", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_name", "instruction_key", "version", name="instructions_app_key_version_unique"),
        schema="negentropy",
    )
    op.create_table(
        "sandbox_executions",
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("sandbox_type", sa.String(length=50), nullable=True),
        sa.Column("code", sa.Text(), nullable=True),
        sa.Column("environment", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("stdout", sa.Text(), nullable=True),
        sa.Column("stderr", sa.Text(), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("execution_time_ms", sa.Float(), nullable=True),
        sa.Column("resource_usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_table(
        "threads",
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_name", "user_id", "id", name="threads_app_user_unique"),
        schema="negentropy",
    )
    op.create_table(
        "tools",
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("openapi_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("permissions", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("call_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("avg_latency_ms", sa.Float(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_name", "name", name="tools_app_name_unique"),
        schema="negentropy",
    )
    op.create_table(
        "traces",
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("span_id", sa.String(length=16), nullable=False),
        sa.Column("parent_span_id", sa.String(length=16), nullable=True),
        sa.Column("operation_name", sa.String(length=255), nullable=False),
        sa.Column("span_kind", sa.String(length=20), server_default="INTERNAL", nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("events", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ns", sa.BigInteger(), nullable=True),
        sa.Column("status_code", sa.String(length=10), server_default="UNSET", nullable=True),
        sa.Column("status_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_table(
        "user_states",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "app_name"),
        schema="negentropy",
    )
    op.create_table(
        "consolidation_jobs",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["negentropy.threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_table(
        "events",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("invocation_id", sa.Uuid(), nullable=False),
        sa.Column("author", sa.String(length=50), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("actions", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("sequence_num", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["negentropy.threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_table(
        "facts",
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("fact_type", sa.String(length=50), server_default="preference", nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding", negentropy.models.base.Vector(), nullable=True),
        sa.Column("confidence", sa.Float(), server_default="1.0", nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["negentropy.threads.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "app_name", "fact_type", "key", name="facts_user_key_unique"),
        schema="negentropy",
    )
    op.create_table(
        "knowledge",
        sa.Column("corpus_id", sa.UUID(), nullable=False),
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", negentropy.models.base.Vector(), nullable=True),
        sa.Column("source_uri", sa.Text(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["corpus_id"], ["negentropy.corpus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_table(
        "memories",
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column("memory_type", sa.String(length=50), server_default="episodic", nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", negentropy.models.base.Vector(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("retention_score", sa.Float(), server_default="1.0", nullable=False),
        sa.Column("access_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["negentropy.threads.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_table(
        "runs",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("thinking_steps", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=True),
        sa.Column("tool_calls", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["negentropy.threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_table(
        "snapshots",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("events_summary", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["negentropy.threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("thread_id", "version", name="snapshots_thread_version_unique"),
        schema="negentropy",
    )
    op.create_table(
        "tool_executions",
        sa.Column("tool_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("input_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tool_id"],
            ["negentropy.tools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    op.create_table(
        "messages",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", negentropy.models.base.Vector(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["negentropy.events.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["thread_id"], ["negentropy.threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="negentropy",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages", schema="negentropy")
    op.drop_table("tool_executions", schema="negentropy")
    op.drop_table("snapshots", schema="negentropy")
    op.drop_table("runs", schema="negentropy")
    op.drop_table("memories", schema="negentropy")
    op.drop_table("knowledge", schema="negentropy")
    op.drop_table("facts", schema="negentropy")
    op.drop_table("events", schema="negentropy")
    op.drop_table("consolidation_jobs", schema="negentropy")
    op.drop_table("user_states", schema="negentropy")
    op.drop_table("traces", schema="negentropy")
    op.drop_table("tools", schema="negentropy")
    op.drop_table("threads", schema="negentropy")
    op.drop_table("sandbox_executions", schema="negentropy")
    op.drop_table("instructions", schema="negentropy")
    op.drop_index(op.f("ix_negentropy_credentials_user_id"), table_name="credentials", schema="negentropy")
    op.drop_index(op.f("ix_negentropy_credentials_credential_key"), table_name="credentials", schema="negentropy")
    op.drop_index(op.f("ix_negentropy_credentials_app_name"), table_name="credentials", schema="negentropy")
    op.drop_table("credentials", schema="negentropy")
    op.drop_table("corpus", schema="negentropy")
    op.drop_table("app_states", schema="negentropy")
    # ### end Alembic commands ###
