"""fix events sequence default

Revision ID: 457c6b429a6a
Revises: b7c1f2e1a4d5
Create Date: 2026-02-04 07:57:51.381181+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Register custom types (e.g. Vector) for Alembic autogenerate
import negentropy.models.base


# revision identifiers, used by Alembic.
revision: str = "457c6b429a6a"
down_revision: Union[str, None] = "b7c1f2e1a4d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.schema.CreateSequence(sa.Sequence("events_sequence_num_seq", schema="negentropy")))
    op.alter_column(
        "events",
        "sequence_num",
        server_default=sa.text("nextval('negentropy.events_sequence_num_seq')"),
        schema="negentropy",
    )
    op.drop_index(op.f("ix_knowledge_graph_runs_app_updated"), table_name="knowledge_graph_runs", schema="negentropy")
    op.drop_index(
        op.f("ix_knowledge_pipeline_runs_app_updated"), table_name="knowledge_pipeline_runs", schema="negentropy"
    )
    op.drop_index(op.f("ix_memory_audit_logs_app_user_created"), table_name="memory_audit_logs", schema="negentropy")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_memory_audit_logs_app_user_created"),
        "memory_audit_logs",
        ["app_name", "user_id", "created_at"],
        unique=False,
        schema="negentropy",
    )
    op.create_index(
        op.f("ix_knowledge_pipeline_runs_app_updated"),
        "knowledge_pipeline_runs",
        ["app_name", "updated_at"],
        unique=False,
        schema="negentropy",
    )
    op.create_index(
        op.f("ix_knowledge_graph_runs_app_updated"),
        "knowledge_graph_runs",
        ["app_name", "updated_at"],
        unique=False,
        schema="negentropy",
    )
    op.alter_column("events", "sequence_num", server_default=None, schema="negentropy")
    op.execute(sa.text("DROP SEQUENCE IF EXISTS negentropy.events_sequence_num_seq"))
    # ### end Alembic commands ###
