"""add tool call stats

Revision ID: de84d2c984fb
Revises: 093a93971bf5
Create Date: 2026-02-03 09:49:38.165174+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Register custom types (e.g. Vector) for Alembic autogenerate
import negentropy.models.base


# revision identifiers, used by Alembic.
revision: str = "de84d2c984fb"
down_revision: Union[str, None] = "093a93971bf5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tools",
        sa.Column("call_count_success", sa.Integer(), server_default="0", nullable=False),
        schema=negentropy.models.base.NEGENTROPY_SCHEMA,
    )
    op.add_column(
        "tools",
        sa.Column("call_count_failed", sa.Integer(), server_default="0", nullable=False),
        schema=negentropy.models.base.NEGENTROPY_SCHEMA,
    )
    op.add_column(
        "tools",
        sa.Column("call_count_denied", sa.Integer(), server_default="0", nullable=False),
        schema=negentropy.models.base.NEGENTROPY_SCHEMA,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tools", "call_count_denied", schema=negentropy.models.base.NEGENTROPY_SCHEMA)
    op.drop_column("tools", "call_count_failed", schema=negentropy.models.base.NEGENTROPY_SCHEMA)
    op.drop_column("tools", "call_count_success", schema=negentropy.models.base.NEGENTROPY_SCHEMA)
    # ### end Alembic commands ###
