"""Initial Schema

Revision ID: ee1226af9efa
Revises: 35879d6b0e12
Create Date: 2026-02-01 08:48:31.321885+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Register custom types (e.g. Vector) for Alembic autogenerate
import negentropy.models.base


# revision identifiers, used by Alembic.
revision: str = "ee1226af9efa"
down_revision: Union[str, None] = "35879d6b0e12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
