# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""媒体固定资产登记制：默认不入库，登记才入库。

音/视频媒体文件（*.mp3/*.mp4/*.wav/…及动图 *.gif）一律默认不进 Git 仓库；
确属公共固定资产的，先在 ``scripts/media-assets.toml`` 登记（path/sha256/
bytes/reason），再由本脚本 ``--sync`` 把白名单重放进 .gitignore，之后正常
``git add``。未登记媒体即便被 ``git add -f`` 强加，``--check`` 也会按
「已入库媒体 ⊆ 登记表」拦下。

设计要点（对齐 check_twin_files.py 的取向）：

* **登记表是唯一事实源** —— .gitignore 的白名单块是登记表的派生产物
  （BEGIN/END 标记块内由 --sync 重写），不手工编辑；扩展名默认忽略段是
  策略（很少变），白名单是数据（随登记变），两段分离。
* **白名单放行必须实测** —— git 的目录级忽略会让内部的 ``!file`` 否定
  永不生效（规则文本看起来对、实际照样挡）。--sync 对每个登记路径跑
  ``git check-ignore`` 确认真的放行，把该陷阱闭合在工具内。
* **可诊断输出** —— 违规时打印「路径 + 应做的动作」，不打印哈希表。

用法::

    uv run --no-project scripts/check_media_assets.py --sync   # 登记表 → .gitignore 白名单
    uv run --no-project scripts/check_media_assets.py --check  # 钩子/CI 校验（退出码表意）

供 pre-commit 钩子与 CI（.github/workflows/media-assets-consistency.yml）双侧调用。
"""

from __future__ import annotations

import argparse
import hashlib
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTRY = REPO_ROOT / "scripts" / "media-assets.toml"
GITIGNORE = REPO_ROOT / ".gitignore"
PRECOMMIT = REPO_ROOT / ".pre-commit-config.yaml"
CI_WORKFLOW = REPO_ROOT / ".github" / "workflows" / "media-assets-consistency.yml"

#: 默认不入库的媒体扩展名（小写；.gitignore 通用段与「已入库 ⊆ 登记表」扫描共用）。
#: 口径：音/视频产物 + 动图（gif）；静态图（png/jpg/svg/webp）不在此列——
#: docs/assets 既有大量入库截图属文档资产，纳入会让登记表变成图片清单。
MEDIA_EXTS = ("mp3", "mp4", "wav", "m4a", "aac", "flac", "ogg", "opus", "webm", "mov", "mkv", "avi", "gif")

BEGIN_MARK = "# BEGIN media-allowlist (generated by scripts/check_media_assets.py --sync; DO NOT EDIT)"
END_MARK = "# END media-allowlist"


def sha256_of(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def load_registry() -> list[dict]:
    with REGISTRY.open("rb") as f:
        data = tomllib.load(f)
    assets = data.get("asset", [])
    seen: set[str] = set()
    for a in assets:
        rel = a["path"]
        if rel in seen:
            raise SystemExit(f"[配置错误] 登记表内路径重复：{rel}")
        seen.add(rel)
        for key in ("sha256", "bytes", "reason"):
            if key not in a:
                raise SystemExit(f"[配置错误] {rel} 缺少字段 {key}")
    return assets


def check_sync(registry: list[dict]) -> list[str]:
    """校验 .gitignore：通用忽略段覆盖全部扩展名，白名单块与登记表一致且放行实测生效。"""
    problems: list[str] = []
    text = GITIGNORE.read_text(encoding="utf-8")

    # ① 通用忽略段：每个扩展名都要有全仓忽略行（防有人删规则让默认忽略失效）。
    for ext in MEDIA_EXTS:
        if f"*.{ext}" not in text:
            problems.append(f".gitignore 缺少通用忽略规则 *.{ext}（默认不入库策略被削弱）")

    # ② 白名单块存在且内容 == 登记表派生值。
    block = render_allowlist(registry)
    if BEGIN_MARK not in text or END_MARK not in text:
        problems.append(".gitignore 缺少白名单标记块——跑 --sync 生成")
    elif block not in text:
        problems.append(".gitignore 白名单块与登记表不一致——跑 --sync 重放")
    elif text.index(END_MARK) < text.index(BEGIN_MARK):
        problems.append(".gitignore 白名单块标记顺序异常（END 在 BEGIN 之前）")

    # ③ 放行实测：登记路径必须真的不被忽略（目录级忽略陷阱在此暴露）。
    for a in registry:
        rel = a["path"]
        probe = subprocess_check_ignore(rel)
        if probe is True:
            problems.append(
                f"{rel} 仍被 .gitignore 忽略——白名单否定行未生效"
                "（多半被某条目录级忽略挡住，git 不再下探该目录；须调整那条目录级规则）"
            )
        elif probe is None:
            problems.append(f"{rel} 无法用 git check-ignore 判定（git 不可用或路径非法）")
    return problems


def render_allowlist(registry: list[dict]) -> str:
    lines = [BEGIN_MARK]
    lines += [f"!{a['path']}" for a in registry]
    lines.append(END_MARK)
    return "\n".join(lines)


def subprocess_check_ignore(rel: str) -> bool | None:
    """git check-ignore -q：<path> 被忽略返回 True，放行返回 False，git 异常返回 None。"""
    import subprocess

    try:
        return subprocess.run(
            ["git", "check-ignore", "-q", rel], cwd=REPO_ROOT, check=False
        ).returncode == 0
    except OSError:
        return None


def check_registry_files(registry: list[dict]) -> list[str]:
    """登记表 ↔ 仓库实态对账：存在性、指纹、是否已入库、已入库面 ⊆ 登记表。"""
    problems: list[str] = []
    tracked = set(tracked_media_files())
    registered = {a["path"] for a in registry}

    for a in registry:
        rel = a["path"]
        p = REPO_ROOT / rel
        if not p.is_file():
            problems.append(f"{rel} 已登记但文件不存在（被删/改名？更新登记表或恢复文件）")
            continue
        digest = sha256_of(p)
        if digest != a["sha256"]:
            problems.append(
                f"{rel} 内容与登记指纹不符（文件被替换？）——更新登记表 sha256/bytes，"
                "或恢复原文件；替换媒体不入登记即静默漂移"
            )
        elif p.stat().st_size != a["bytes"]:
            problems.append(f"{rel} 字节数与登记不符（sha256 一致却 size 不同=登记表手误）")
        if rel not in tracked:
            problems.append(f"{rel} 已登记但未入 Git（git add 过了吗？登记与入库必须同时生效）")

    for rel in sorted(tracked - registered):
        problems.append(f"{rel} 已入 Git 但不在登记表——先登记（含 sha256/bytes/reason）再入库，或 git rm --cached 移出")
    return problems


def tracked_media_files() -> list[str]:
    """git ls-files 里的媒体文件（大小写不敏感按扩展名过滤）。"""
    import subprocess

    out = subprocess.run(
        ["git", "ls-files"], cwd=REPO_ROOT, check=False, capture_output=True, text=True
    ).stdout
    suffixes = tuple("." + e for e in MEDIA_EXTS)
    return [
        ln for ln in out.splitlines()
        if ln.lower().endswith(suffixes)
    ]


def check_trigger_coverage(registry: list[dict]) -> list[str]:
    """自检：登记路径都须出现在 pre-commit files 正则与 CI paths 里（同 twin 教训：
    独立于登记表的第二/第三份清单，漏配则执法对该文件静默失效）。"""
    problems: list[str] = []
    watchers = {"pre-commit": PRECOMMIT, "CI workflow": CI_WORKFLOW}
    for label, path in watchers.items():
        if not path.is_file():
            problems.append(f"{label} 文件不存在，无法确认触发覆盖")
            continue
        text = path.read_text(encoding="utf-8")
        for a in registry:
            rel = a["path"]
            # pre-commit 正则里 `.` 写作 `\.`，两种写法均视为已覆盖。
            if rel not in text and rel.replace(".", r"\.") not in text:
                problems.append(f"{label} 未覆盖登记路径：{rel}")
    return problems


def cmd_sync() -> int:
    registry = load_registry()
    text = GITIGNORE.read_text(encoding="utf-8")
    block = render_allowlist(registry)
    if BEGIN_MARK in text and END_MARK in text:
        pre = text[: text.index(BEGIN_MARK)]
        post = text[text.index(END_MARK) + len(END_MARK):]
        new_text = pre + block + post
    else:
        new_text = text.rstrip("\n") + "\n\n" + block + "\n"
    GITIGNORE.write_text(new_text, encoding="utf-8")

    problems = check_sync(registry) + check_registry_files(registry)
    for p in problems:
        print(f"✗ {p}", file=sys.stderr)
    if problems:
        print("\n--sync 已重放白名单，但存在未解决问题（见上）；修正后重跑。", file=sys.stderr)
        return 1
    print(f"✓ 白名单已重放（{len(registry)} 项），放行实测与登记对账全过")
    return 0


def cmd_check() -> int:
    registry = load_registry()
    problems = check_sync(registry) + check_registry_files(registry) + check_trigger_coverage(registry)
    for p in problems:
        print(f"✗ {p}", file=sys.stderr)
    if problems:
        print(
            "\n媒体资产登记对账未过。新增/替换媒体：先登记 scripts/media-assets.toml，"
            "再跑 scripts/check_media_assets.py --sync，然后 git add。",
            file=sys.stderr,
        )
        return 1
    print(f"✓ 媒体资产登记对账通过（登记 {len(registry)} 项 = 已入库媒体面）")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="媒体固定资产登记制：--sync 生成白名单 / --check 对账")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--sync", action="store_true", help="按登记表重放 .gitignore 白名单并对账")
    mode.add_argument("--check", action="store_true", help="校验登记表↔仓库实态（pre-commit/CI 用）")
    args = parser.parse_args()
    return cmd_sync() if args.sync else cmd_check()


if __name__ == "__main__":
    sys.exit(main())
